bashtage/linearmodels

examples/iv_basic-examples.ipynb, experiment.py, linearmodels/iv/data.py, linearmodels/iv/model.py, linearmodels/iv/tests/test_data.py, linearmodels/iv/tests/test_model.py
Rename DataHandler to IVData
Handle string data columns as categoricals
Add example using a categorical
=> ENH: Add string handling for data

linearmodels/iv/_utility.py, linearmodels/iv/data.py, linearmodels/iv/tests/test_data.py
Change sring detection ot be more robist
Fix big which silently dropped NA
=> REF: Fix data string detection

linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/panel/tests/test_data.py, linearmodels/panel/tests/test_model.py
Change main shape in PanelDataHandler so that 3d input is vars x time x entities
Make multiindex dataframe the authoritative view of the data.
=> Refactor panel data

doc/source/panel/covariance.rst, doc/source/panel/data.rst, doc/source/panel/models.rst, doc/source/panel/panel.rst, experiment.py, linearmodels/panel/data.py, linearmodels/panel/tests/test_data.py
Add time and entity fixed effect removal
=> ENH: Add basic fixed effect removal

linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/tests/panel/test_model.py
Add additional transformations to PanelData
Remove all use of intercept
=> REF: Remove intercept and augment PanelData

linearmodels/panel/model.py, linearmodels/tests/panel/test_model.py
Add support for weights -- not implmented in models, just the interface
Add initial formula support for panel models
=> ENH: Add initial support for weights

experiment.py, linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/tests/iv/results/execute-stata-simulated-data.py, linearmodels/tests/iv/results/read_stata_results.py, linearmodels/tests/iv/test_data.py, linearmodels/tests/iv/test_model.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/test_data.py, linearmodels/tests/panel/test_model.py, linearmodels/tests/test_utility.py
Fix two-way demeaning to allow entity/time effects
=> BUG: Fix two-way demeaning

README.md
Clean readme or extraneous text
[skip ci]
=> DOC: Cleanup readme

experiment.py, linearmodels/iv/results.py, linearmodels/panel/model.py, linearmodels/panel/results.py, linearmodels/tests/panel/_utility.py, linearmodels/utility.py
=> ENH: Add summary for panel models

linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/tests/panel/test_data.py, linearmodels/tests/panel/test_model.py
Improve testing of data, fixing bugs
Improve testing of models
=> TST: Improve testing of data and models

linearmodels/panel/model.py, linearmodels/panel/results.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/test_between_ols.py, linearmodels/tests/panel/test_pooled_ols.py
Test pooled ols against standard OLS
=> TST: Test Pooled agsinst OLS

experiment.py, linearmodels/iv/model.py, linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/test_panel_ols.py
Test alternative configuations of PanelOLS
Add path for weighted PanelOLS that uses FWL
=> TST: Test PanelOLS

linearmodels/iv/model.py, linearmodels/panel/covariance.py, linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/utility.py
Test PanelOLS for effects and weights.
=> TST: Test PanelOLS with effects and weights

experiment.py, linearmodels/iv/data.py, linearmodels/panel/covariance.py, linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/test_data.py, linearmodels/tests/panel/test_panel_covariance.py
Add ability to pass other effects to PanelOLS
Add heteroskedastic covariance
Add one-way cluster covariance
=> ENH: Add generic effects

linearmodels/panel/results.py
=> ENH: Add f-stat to summary table

linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/panel/results.py, linearmodels/tests/panel/test_between_ols.py, linearmodels/tests/panel/test_data.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/panel/test_pooled_ols.py, linearmodels/utility.py
Fix incorrect demeaning
Verify alternative R2 correctness
=> FIX: Fix and verify R2 measure correctness

linearmodels/iv/model.py, linearmodels/iv/results.py, linearmodels/panel/model.py, linearmodels/panel/results.py, linearmodels/tests/iv/test_model.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/test_between_ols.py, linearmodels/tests/panel/test_data.py, linearmodels/tests/panel/test_firstdifference_ols.py, linearmodels/tests/panel/test_model.py, linearmodels/tests/panel/test_panel_covariance.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/panel/test_pooled_ols.py, linearmodels/tests/test_utility.py
Add tests of residuals against simple WLS model residuals
=> TST: Test model residials

linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/panel/results.py, linearmodels/tests/panel/test_between_ols.py, linearmodels/tests/panel/test_firstdifference_ols.py, linearmodels/tests/panel/test_model.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/panel/test_pooled_ols.py
Add doc strings explaining result elements
=> DOC: Add docstrings to results

experiment.py, linearmodels/panel/covariance.py, linearmodels/tests/panel/test_panel_covariance.py
Add two-way clustered covariance
=> ENH: Add two-way covariance

linearmodels/panel/covariance.py, linearmodels/panel/model.py, linearmodels/tests/panel/test_between_ols.py, linearmodels/tests/panel/test_panel_covariance.py, linearmodels/tests/panel/test_pooled_ols.py
Test equivalence between estiamtors
Fix bugs in clustered estimators
Add ability to cluster by time/entity to pooled OLS
Add clustering to BetweenOLS
=> TST: Test equivalence between panel models and OLS

doc/source/iv/covariance.rst, doc/source/iv/introduction.rst, linearmodels/iv/covariance.py, linearmodels/iv/model.py, linearmodels/panel/covariance.py, linearmodels/panel/model.py, linearmodels/tests/iv/test_covariance.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/test_between_ols.py, linearmodels/tests/panel/test_firstdifference_ols.py, linearmodels/tests/panel/test_model.py, linearmodels/tests/panel/test_pooled_ols.py
Test equivalence with OLS estimators
=> Covariance equivalence testing

linearmodels/tests/panel/test_between_ols.py, linearmodels/tests/panel/test_firstdifference_ols.py, linearmodels/tests/panel/test_panel_ols.py
Test Panel covariance equivalence
Add additional tests for error conditions
=> TST: Test panel covariance equiv

linearmodels/iv/gmm.py, linearmodels/panel/covariance.py, linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/tests/iv/test_gmm.py, linearmodels/tests/iv/test_model.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/test_between_ols.py, linearmodels/tests/panel/test_data.py, linearmodels/tests/panel/test_panel_covariance.py, linearmodels/tests/panel/test_panel_ols.py
Test standard errors in PanleOLS agaains OLS w/ dummies
Add additioanl test for small missed in code
=> TST: Test cluster standard errors in PanelOLS

experiment.py, linearmodels/panel/covariance.py, linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/panel/results.py, linearmodels/tests/iv/test_gmm.py, linearmodels/tests/iv/test_model.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/test_between_ols.py, linearmodels/tests/panel/test_firstdifference_ols.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/panel/test_pooled_ols.py, linearmodels/utility.py
Normalize cluster inputs
Add pooled f-statistic
Add classic f-statistic
=> ENH: Normalize clusters

linearmodels/panel/model.py, linearmodels/tests/panel/test_data.py, linearmodels/tests/panel/test_formula.py, linearmodels/tests/panel/test_model.py, linearmodels/tests/panel/test_panel_ols.py
Refactor inheritance to remove meaningless properties
=> REF: Refactor inheritance

linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/tests/panel/test_cluster_input_formats.py
Test string, int and cat inputs and mixes
=> TST: Test alternative formats for cluster/effects

experiment.py, linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/panel/results.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/test_data.py, linearmodels/tests/panel/test_firstdifference_ols.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/test_utility.py, linearmodels/utility.py
Add new results class for irrelevant tests
Add doc string improvements ot dat aand results
Improve summary
=> ENH: Add new test class

linearmodels/__init__.py, linearmodels/tests/panel/test_panel_ols.py
Add a direct test for pooled effects
=> TST: test f pooled directly

experiment.py, linearmodels/panel/model.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/panel/test_simulated_against_stata.py
Enable a framework to handle degree of freedom corrections
=> ENH: Enable minimal degree of freedome correction

experiment.py, linearmodels/panel/covariance.py, linearmodels/panel/model.py
Add automatic df adjustment for PanelOLS with clustered
=> ENH: Add automatic df adjustment

linearmodels/panel/data.py, linearmodels/tests/panel/test_data.py
Use grouby demean to do entity/time demeaning
=> REF: Use groupby demean for speed

linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/tests/panel/test_data.py
Add two-way demeaning using iterative method
Add case to fast path
=> ENH: Add multi-way demean using MAC and groupby

linearmodels/panel/data.py, linearmodels/tests/panel/test_panel_ols.py
Set the index in the generic demean groupby to improve performance
Add additional tests to ensure rare paths are taken
=> PERF: Improve performance of groupby using index

experiment-2.py, linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/test_data.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/test_examples.py
Add weighted demean using only groupby
Add MAC-based multi-way weighted demeaning
Add fast path for weighted models
=> ENH: Add weighted demean

linearmodels/panel/covariance.py, linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/test_model.py, linearmodels/tests/panel/test_panel_covariance.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/panel/test_simulated_against_stata.py, linearmodels/tests/test_utility.py, linearmodels/utility.py
Refactor location of CovarianceManager
Test covariance manager
Add tsts for missing paths
Remove unreachable code
=> REF/TST:  Refactor location of CovMan and rest

linearmodels/panel/covariance.py, linearmodels/panel/model.py, linearmodels/panel/results.py
Improve doc strings for model, data and results
=> DOC: Improve docstrings

README.md, README.rst, doc/source/iv/index.rst, doc/source/panel/covariance.rst, doc/source/panel/data.rst, doc/source/panel/faq.rst, doc/source/panel/index.rst, doc/source/panel/models.rst, doc/source/panel/pandas.rst, doc/source/panel/results.rst, examples/panel_using-formulas.ipynb, linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/panel/results.py
Add rsquared including effects for panel models
Improve return description to avoid warnings in PyCharm
Substantially improve the documentation
Allow other effects to be added to a formula in PanelOLS
=> ENH/DOC: Add additional R squared and docs

examples/panel_data-formats.ipynb, experiment-2.py, linearmodels/panel/covariance.py, linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/tests/panel/test_data.py
Prevent data index overwirte in model
=> BUG: Prevent data overwrite

experiment-2.py, linearmodels/panel/model.py, linearmodels/panel/results.py, linearmodels/tests/panel/test_data.py
Return effects are part of results
=> ENH: Add effects to results

experiment-2.py, linearmodels/panel/model.py, linearmodels/tests/panel/test_panel_ols.py
Add small sample SA method
Add tests for rsquared inclusive
=> ENH/TST: Add small sample adj for RE

linearmodels/compat/pandas.py, linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/tests/panel/test_cluster_input_formats.py, linearmodels/tests/panel/test_data.py
Check other effects for being nested within each other
Ensure time index is datetime or numeric
=> ENH: Check categoricals for nesting

experiment-2.py, linearmodels/panel/results.py, linearmodels/tests/panel/test_results.py
Add method to compare panel models
=> ENH: Add Panel compare

doc/source/panel/covariance.rst, linearmodels/compat/pandas.py, linearmodels/datasets/wage_panel/__init__.py, linearmodels/iv/covariance.py, linearmodels/iv/data.py, linearmodels/iv/gmm.py, linearmodels/iv/results.py, linearmodels/panel/__init__.py, linearmodels/panel/covariance.py, linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/panel/results.py, linearmodels/tests/iv/test_covariance.py, linearmodels/tests/iv/test_gmm.py, linearmodels/tests/panel/test_cluster_input_formats.py, linearmodels/tests/panel/test_data.py, linearmodels/tests/panel/test_formula.py, linearmodels/tests/panel/test_panel_covariance.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/panel/test_random_effects.py, linearmodels/tests/panel/test_results.py, linearmodels/utility.py
Add Driscoll-Kraay Covariance
Refactor comparrisons to use common code
Refactor general demeanining
=> ENH: Add Driscoll-Kraay Covariance

doc/source/index.rst, doc/source/iv/estimators.lyx, doc/source/iv/estimators.tex, doc/source/iv/estimators.txt, doc/source/plan.rst, examples/iv_basic-examples.ipynb, examples/iv_using-formulas.ipynb, examples/panel_data-formats.ipynb, examples/panel_examples.ipynb, examples/panel_using-formulas.ipynb, experiment-2.py, experiment.py, linearmodels/compat/statsmodels.py, linearmodels/datasets/fertility/__init__.py, linearmodels/datasets/mroz/__init__.py, linearmodels/datasets/wage_panel/__init__.py, linearmodels/iv/results.py, linearmodels/panel/__init__.py, linearmodels/panel/model.py, linearmodels/panel/results.py, linearmodels/tests/panel/test_cluster_input_formats.py, linearmodels/tests/panel/test_formula.py, linearmodels/tests/panel/test_model.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/panel/test_results.py, linearmodels/tests/panel/test_simulated_against_stata.py
Add examples
General documentation fixes
=> DOC: Add examples for panel models

linearmodels/panel/data.py, linearmodels/tests/panel/test_data.py
Fix bug related to regression in pandas 0.20
=> BUG: Fix indexing issue due to changesin pandas

experiment-2.py, linearmodels/__init__.py, linearmodels/iv/model.py, linearmodels/panel/model.py, linearmodels/tests/iv/test_model.py, linearmodels/tests/panel/test_between_ols.py, linearmodels/tests/panel/test_data.py, linearmodels/tests/panel/test_simulated_against_stata.py, linearmodels/tests/test_examples.py, linearmodels/tests/test_utility.py, linearmodels/utility.py
Add global flag to disable warnings
Clean up noisy tests
=> ENH: Add global flag to disable warnings

examples/iv_advanced-examples.ipynb, examples/iv_basic-examples.ipynb, examples/iv_using-formulas.ipynb, linearmodels/iv/model.py, linearmodels/iv/results.py, linearmodels/panel/model.py, linearmodels/tests/iv/test_model.py, linearmodels/tests/iv/test_postestimation.py, linearmodels/tests/panel/test_between_ols.py, linearmodels/tests/panel/test_firstdifference_ols.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/panel/test_pooled_ols.py
Require fit optional parameters to be keyword arguments
Improve IV comparrison
More work on IV examples
=> ENH: Require keyword arguments in IV models

linearmodels/compat/pandas.py, linearmodels/iv/_utility.py, linearmodels/iv/data.py, linearmodels/iv/gmm.py, linearmodels/iv/model.py, linearmodels/iv/results.py, linearmodels/tests/iv/test_formulas.py, linearmodels/tests/iv/test_model.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/utility.py
Test formulas when there are no exogenous
Misc test improvements
=> Test formulas no exog

linearmodels/asset_pricing/model.py, linearmodels/panel/covariance.py, linearmodels/tests/asset_pricing/_utility.py, linearmodels/tests/asset_pricing/test_model.py
Add data generator to test models
Add smoke test for models
=> ENH: Add data generator to test asset pricing models

doc/source/iv/introduction.rst, doc/source/panel/introduction.rst, doc/source/panel/pandas.rst, linearmodels/asset_pricing/model.py, linearmodels/asset_pricing/results.py, linearmodels/iv/results.py, linearmodels/panel/results.py, linearmodels/tests/asset_pricing/_utility.py, linearmodels/tests/asset_pricing/test_model.py
Add results class for asset pricing models
=> ENH: Add results for aet pricing models

doc/source/asset_pricing/mathematical-detail.lyx, linearmodels/asset_pricing/model.py, linearmodels/asset_pricing/results.py, linearmodels/tests/asset_pricing/test_model.py
Add formal tests using equivalence
Add some documentation for CS model
=> TST: Add tests for traded factor model

doc/source/asset_pricing/index.rst, doc/source/asset_pricing/mathematical-detail.lyx, doc/source/changes.rst, doc/source/index.rst, doc/source/plan.rst, linearmodels/asset_pricing/model.py, linearmodels/asset_pricing/results.py, linearmodels/tests/asset_pricing/test_model.py
Add 2-step asset pricing estimator
Add to documents
Minor renames
=> ENH: Add 2-step asset pricing estimator

doc/source/asset-pricing/mathematical-detail.lyx, doc/source/asset-pricing/mathematical-detail.lyx~, doc/source/asset-pricing/mathematical-detail.txt, doc/source/asset-pricing/models.rst, doc/source/index.rst, linearmodels/asset_pricing/model.py, linearmodels/asset_pricing/results.py, linearmodels/tests/asset_pricing/test_model.py
Add GMM estimator for linear factor models
=> ENH: Add GMM estimation of models

doc/source/asset-pricing/mathematical-detail.lyx, doc/source/asset-pricing/mathematical-detail.lyx~, doc/source/asset-pricing/mathematical-detail.txt, linearmodels/tests/asset_pricing/test_model.py
Add smoke tests to ensure all paths can be run
Small improvement to document
=> ENH: Add additional smoke tests

linearmodels/asset_pricing/model.py, linearmodels/tests/asset_pricing/test_model.py
=> ENH: Add CUE estimator to GMM Estimator

linearmodels/asset_pricing/__init__.py, linearmodels/asset_pricing/model.py, linearmodels/asset_pricing/results.py, linearmodels/compat/pandas.py, linearmodels/datasets/french/__init__.py, linearmodels/panel/model.py, linearmodels/tests/asset_pricing/_utility.py, linearmodels/tests/asset_pricing/test_formulas.py, linearmodels/tests/asset_pricing/test_model.py, linearmodels/tests/iv/test_data.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/test_data.py
Add formulas
Add data checks
Rename and relocate risk free rate estimation
=> ENH: Add formulas for asset pricing models

linearmodels/asset_pricing/covariance.py, linearmodels/asset_pricing/model.py, linearmodels/tests/asset_pricing/test_model.py
Ensure all covariance options
Add additional weighting options
=> ENH: Add additional covariance options

linearmodels/__init__.py, linearmodels/asset_pricing/covariance.py, linearmodels/asset_pricing/model.py, linearmodels/tests/asset_pricing/test_covariance.py, linearmodels/tests/asset_pricing/test_model.py
Add tests to ensure eror conditions are hit
=> TST: Add tests for errors

doc/source/asset-pricing/mathematical-detail.lyx, doc/source/asset-pricing/mathematical-detail.txt, doc/source/iv/estimators.lyx, doc/source/iv/estimators.txt, examples/asset-pricing_formulas.ipynb, linearmodels/asset_pricing/model.py, linearmodels/tests/test_examples.py, linearmodels/utility.py
Add 3-step regression estimator
Add GLS
=> ENH: Add 3 step estimator

doc/rtd-requirements.txt
Add RTD requirements
[skip ci]
=> DOC: Add requirements for RTD

examples/iv_advanced-examples.ipynb, examples/panel_examples.ipynb
Use print to avoid html formatting
=> DOC: Fix output errors in examples

.gitignore, .travis.yml, doc/source/_static/css/overrides.css, doc/source/asset-pricing/mathematical-detail.lyx, doc/source/asset-pricing/mathematical-detail.txt, doc/source/asset-pricing/mathematical-formula.rst, examples/asset-pricing_examples.ipynb, examples/asset-pricing_formulas.ipynb, linearmodels/asset_pricing/model.py, linearmodels/conftest.py, linearmodels/panel/covariance.py, linearmodels/panel/model.py, linearmodels/tests/asset_pricing/test_formulas.py, linearmodels/tests/panel/test_panel_covariance.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/test_examples.py
Add AC robust covariance w/o cross-sectional dependence
Update documentation
=> ENH: Add autocorrelation robust covariance

linearmodels/tests/panel/test_model.py
Skip test that is not relevant with current pandas
=> BUG: Fix warning bug

linearmodels/iv/data.py, linearmodels/panel/data.py
Defer xarray import until required
=> REF: Defer import of xarray until needed

linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/tests/panel/test_between_ols.py, linearmodels/tests/panel/test_data.py, linearmodels/tests/panel/test_panel_ols.py
Remvoe internal use of Panel while retaining Panel
as a valid external data format
=> REF: Remove core dependency on Panel

linearmodels/compat/pandas.py, linearmodels/tests/iv/test_data.py
Avoid unsupported api function
=> CLN: Refactor pandas imports to avoid unsupported

linearmodels/tests/asset_pricing/test_covariance.py, linearmodels/tests/datasets/test_datasets.py, linearmodels/tests/panel/test_fama_macbeth.py, linearmodels/tests/system/test_model.py
Add testing for various errors that have been missed
=> TST: Extend testing into edge cases

.travis.yml, README.md, linearmodels/iv/data.py, linearmodels/panel/data.py, linearmodels/tests/iv/test_data.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/test_between_ols.py, linearmodels/tests/panel/test_cluster_input_formats.py, linearmodels/tests/panel/test_data.py, linearmodels/tests/panel/test_fama_macbeth.py, linearmodels/tests/panel/test_firstdifference_ols.py, linearmodels/tests/panel/test_formula.py, linearmodels/tests/panel/test_model.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/panel/test_pooled_ols.py, linearmodels/tests/panel/test_random_effects.py, linearmodels/tests/test_examples.py, requirements.txt
Do not require xarray and skip unless available
=> ENH: Make xarray an optional dependency

linearmodels/tests/asset_pricing/test_model.py, linearmodels/tests/iv/test_against_stata.py, linearmodels/tests/iv/test_missing_data.py, linearmodels/tests/iv/test_model.py, linearmodels/tests/panel/test_between_ols.py, linearmodels/tests/panel/test_cluster_input_formats.py, linearmodels/tests/panel/test_data.py, linearmodels/tests/panel/test_fama_macbeth.py, linearmodels/tests/panel/test_firstdifference_ols.py, linearmodels/tests/panel/test_formula.py, linearmodels/tests/panel/test_model.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/panel/test_pooled_ols.py, linearmodels/tests/panel/test_random_effects.py, linearmodels/tests/panel/test_simulated_against_stata.py, linearmodels/tests/system/test_against_stata.py
Filter missing data warnings from pytest output
=> TST: Filter MissingDataWarnings

linearmodels/system/_utility.py
Protect rank to remove warning
=> CLN: Protect rank against NaN

.travis.yml, README.md, README.rst, requirements-dev.txt, requirements.txt
Update formal dependencies to track releases of SciPy and Pandas
=> TST: Update dependencies

examples/system_three-stage-least-squares.ipynb, linearmodels/system/model.py
=> TST/EXAMPLE: Test 3SLS

.travis.yml, linearmodels/system/_utility.py, linearmodels/tests/iv/results/read_stata_results.py, linearmodels/tests/panel/test_data.py
Broken test did not raise on previous xarray
Add testing for xarray 0.9 and 0.10
=> TST:  Fix broken test

linearmodels/__init__.py, linearmodels/system/gmm.py, linearmodels/system/model.py, linearmodels/tests/system/test_gmm.py
Test errors are raised
Test initial weights are used
Test that estimator works without a constant
Test weights options are used
xref #111
=> TST: Test edge features of IV System GMM estimator

linearmodels/system/_utility.py, linearmodels/system/covariance.py, linearmodels/system/model.py, linearmodels/tests/system/test_utility.py
Use a single function for blocked cross products to simplify
xref #111
=> CLN: Simplify blocked cross produces

linearmodels/system/covariance.py, linearmodels/system/gmm.py, linearmodels/system/model.py, linearmodels/system/results.py, linearmodels/tests/system/_utility.py, linearmodels/tests/system/test_gmm.py, linearmodels/tests/test_utility.py, linearmodels/utility.py
Print covariance estimator and weight information in summary
Add str and repr to covariance and weight
xref #111
=> ENH: Add covariance and weight to summary

linearmodels/system/covariance.py, linearmodels/system/gmm.py, linearmodels/system/model.py, linearmodels/tests/system/test_gmm.py
Add tests for fixed sigma in GMM estimation
Add tests for repr for GMM weighting matrices
xref #111
=> TST: Test fixed sigma

examples/system_three-stage-ls.ipynb
Add example showing System GMM estimation
=> EXAMPLE: Add System GMM to examples

linearmodels/iv/results.py, linearmodels/system/model.py, linearmodels/system/results.py, linearmodels/tests/system/_utility.py, linearmodels/tests/system/test_covariance.py, linearmodels/tests/system/test_gmm.py
Add system J-statistic
xref #111
=> ENH: Add J-statistic for System GMM

linearmodels/asset_pricing/covariance.py, linearmodels/asset_pricing/model.py
Refactor covariance for HAC estimation to share code
Refactor formula code to share code
xref #89
=> REF: Refactor common code out of asset pricing

linearmodels/system/model.py, linearmodels/tests/system/test_gmm.py
Allow constraints to be used for parameter estimation in GMM
Refactor constrained optimization to a single function
=> ENH: Add constrained estimation to GMM

linearmodels/system/model.py
Remvoe DoF charge for constraints in J test
=> BUG: Account for constraints in J test

linearmodels/asset_pricing/covariance.py, linearmodels/iv/covariance.py, linearmodels/panel/covariance.py, linearmodels/system/_utility.py, linearmodels/system/covariance.py, linearmodels/system/gmm.py, linearmodels/system/model.py, linearmodels/tests/system/test_gmm.py, linearmodels/tests/system/test_sur.py
Add HAC estimator for both SUR and IV3SLS
=> ENH: Add HAC covariance estimator for system

linearmodels/iv/gmm.py, linearmodels/system/gmm.py, linearmodels/tests/iv/test_gmm.py
Enable optimal bandidth for GMM estimation
=> ENH: Enable optimal bandwidth for GMM estimation

linearmodels/conftest.py, linearmodels/tests/system/test_gmm.py
Test optuoanl bandwidth for errors
=> TST: Add test to ensure optimal bandwidth is executed

linearmodels/tests/system/test_gmm.py
Add test to ensure optimal BW code runs
=> TST: Add test that wil help optimal BW

doc/source/system/covariance.rst, doc/source/system/gmm-weights.rst, doc/source/utility.rst, linearmodels/system/covariance.py, linearmodels/system/gmm.py, linearmodels/system/model.py, linearmodels/system/results.py, linearmodels/tests/system/test_gmm.py, linearmodels/utility.py
Improve testing of kernel weighting
Add kernel covariance and weight to docs
Fix errors and omissions in weights
=> TST/DOC: Improve kernel covariance and weight

.travis.yml, doc/source/changes.rst, doc/source/iv/estimators.lyx, doc/source/iv/estimators.txt, doc/source/iv/introduction.rst, doc/source/panel/introduction.rst, doc/source/system/covariance.rst, doc/source/system/mathematical-detail.lyx, doc/source/system/mathematical-detail.txt, doc/source/system/results.rst, examples/iv_advanced-examples.ipynb, examples/panel_examples.ipynb, linearmodels/asset_pricing/covariance.py, linearmodels/asset_pricing/model.py, linearmodels/datasets/fringe/__init__.py, linearmodels/iv/_utility.py, linearmodels/iv/covariance.py, linearmodels/iv/results.py, linearmodels/panel/covariance.py, linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/system/_utility.py, linearmodels/system/covariance.py, linearmodels/system/gmm.py, linearmodels/system/model.py, linearmodels/system/results.py, linearmodels/tests/system/results/execute-stata.py, linearmodels/tests/system/results/generate_data.py, linearmodels/tests/system/test_covariance.py, linearmodels/tests/system/test_gmm.py
Test covariance using direct tests
Test weights using direct tests
Numerous spelling fixed
=> Direct cov test

.travis.yml
Ensure docs are correctly built
=> BLD: Ensure docs are correctly built

.travis.yml
Ensure doc build is correct for tagged builds
=> BLD: Fix doc buidl for tagged commits

linearmodels/_version.py, linearmodels/panel/model.py, linearmodels/panel/results.py, linearmodels/tests/iv/test_data.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/test_between_ols.py, linearmodels/tests/panel/test_fama_macbeth.py, linearmodels/tests/panel/test_firstdifference_ols.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/panel/test_pooled_ols.py, linearmodels/tests/panel/test_random_effects.py, linearmodels/tests/panel/test_results.py, linearmodels/tests/system/results/execute-stata-3sls.py, linearmodels/tests/system/results/generate_data.py
Add fitted_values, effects and idiosyncratic residuals to outputs to panel results
Add predict to panel results
=> ENH: Add fitted_values and related

linearmodels/iv/model.py, linearmodels/iv/results.py, linearmodels/tests/iv/test_results.py, linearmodels/tests/panel/test_results.py
Add predict to univariate IV estimators
Add fitted values to univariate IV estimators
xref #130
xred #98
xref #96
=> ENH: Add predict to univariate IV estimators

linearmodels/iv/results.py, linearmodels/system/model.py, linearmodels/system/results.py, linearmodels/tests/system/test_3sls.py, linearmodels/tests/system/test_gmm.py, linearmodels/tests/system/test_sur.py
Add predict and fitted values to system estimators
=> ENH: Add predict to system estimators

linearmodels/iv/_utility.py, linearmodels/iv/model.py, linearmodels/iv/results.py, linearmodels/system/results.py, linearmodels/tests/iv/test_formulas.py
Add out-of-sample prediction to IV models
=> ENH: Add out-of-sample prediction to IV

linearmodels/iv/_utility.py, linearmodels/iv/model.py, linearmodels/panel/model.py, linearmodels/panel/results.py, linearmodels/tests/panel/test_formula.py
All data to be used with predict to produce out-of-sample fits
=> ENH: Add out-of-sample prediction to panel

linearmodels/formula.py, linearmodels/iv/_utility.py, linearmodels/system/model.py, linearmodels/system/results.py, linearmodels/tests/system/_utility.py, linearmodels/tests/system/test_3sls.py, linearmodels/tests/system/test_formulas.py
Allow data to be passed which enables out-of-sample prediction in system estimators
=> ENH: Add out-of-sample prediction to System mdoels

linearmodels/formula.py, linearmodels/iv/_utility.py, linearmodels/panel/model.py, linearmodels/tests/panel/test_formula.py
Add weight support to FamaMacBeth regression
=> ENH: Add weight support to FamaMacBeth

linearmodels/system/model.py, linearmodels/tests/panel/test_formula.py, linearmodels/tests/system/test_formulas.py
Allow env to be changed for system formulas
Add doc string for predict
Test rare predict paths
Test rare formula parser paths
=> ENH: Allow env to be set for SystemFormulas

.travis.yml, README.md, linearmodels/asset_pricing/model.py, linearmodels/compat/numpy.py, linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/system/model.py, linearmodels/tests/asset_pricing/test_linear_factor_model.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/results/parse_stata_results.py, linearmodels/tests/panel/test_data.py, linearmodels/tests/panel/test_fama_macbeth.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/utility.py
Improve PanelOLS performance on large datasets
Clean FutureWarnings
Update build dependencies
=> Perf panel ols

README.rst, linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/utility.py
Improve performance by optmizing Panel object creation
=> ENH: Improve performance of PanelOLS

linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/utility.py
Improve performance of panel model estimator
=> PERF: Improve performance

doc/source/changes.rst, linearmodels/iv/_utility.py, linearmodels/tests/iv/test_formulas.py
Fix bug with single character names in either instrument
or regressor
closes #149
=> BUG: Fix bus with single character names

linearmodels/panel/data.py, linearmodels/panel/model.py
Improve performance when using from formula by avoiding unnecessary
copying and parsing
xref #152
=> PERF: Improve performance when using from_formula

doc/source/changes.rst, linearmodels/panel/data.py, linearmodels/tests/panel/test_data.py
Preserve index names when these have been provided
=> ENH: Preserve index names

.travis.yml, ci/install-from-conda.sh, ci/install-from-pypi.sh, doc/source/changes.rst
Install packages from PyPI to get alternative BLAS
=> TST: Add test run from PyPI

.travis.yml, ci/install-from-conda.sh, linearmodels/tests/system/test_utility.py
Force use of OpenBLAS through conda
Fix small failure due to pandas reduction operator inconsistency
=> TEST: Add OpenBLAS/conda

.lgtm.yml, .travis.yml, README.md, README.rst, doc/source/changes.rst, doc/source/plan.rst, linearmodels/compat/pandas.py, linearmodels/iv/data.py, linearmodels/panel/data.py, linearmodels/panel/results.py, linearmodels/system/results.py, linearmodels/tests/asset_pricing/test_formulas.py, linearmodels/tests/iv/test_data.py, linearmodels/tests/iv/test_formulas.py, linearmodels/tests/iv/test_results.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/results/generate-panel-data.py, linearmodels/tests/panel/test_data.py, linearmodels/tests/panel/test_formula.py, linearmodels/tests/panel/test_results.py, linearmodels/tests/system/results/execute-stata-3sls.py, linearmodels/tests/system/results/generate_data.py, linearmodels/tests/system/test_3sls.py, linearmodels/tests/system/test_3sls_against_stata.py, linearmodels/tests/system/test_formulas.py, linearmodels/tests/system/test_gmm.py, linearmodels/tests/system/test_sur.py, linearmodels/tests/test_compat.py, linearmodels/utility.py
=> RLS: Release 4.9 commit

linearmodels/asset_pricing/model.py, linearmodels/panel/data.py, linearmodels/system/_utility.py, linearmodels/system/covariance.py, linearmodels/system/model.py, linearmodels/tests/asset_pricing/test_linear_factor_model.py, linearmodels/tests/iv/results/read_stata_results.py, linearmodels/tests/panel/test_cluster_input_formats.py, linearmodels/tests/system/results/parse_stata_results.py, linearmodels/utility.py
Add short circuits when applicable to multivariate OLS
General clean up of small issues
closes #158
=> PERF: Improve performance of multivarite OLS

doc/source/conf.py, doc/source/iv/index.rst, doc/source/panel/index.rst, examples/iv_advanced-examples.ipynb, examples/iv_basic-examples.ipynb, examples/system_examples.ipynb, linearmodels/asset_pricing/model.py, linearmodels/asset_pricing/results.py, linearmodels/iv/data.py, linearmodels/iv/model.py, linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/system/model.py, linearmodels/tests/asset_pricing/test_covariance.py, linearmodels/tests/asset_pricing/test_formulas.py, linearmodels/tests/iv/test_results.py, linearmodels/tests/panel/test_between_ols.py, linearmodels/tests/panel/test_panel_covariance.py, linearmodels/tests/system/results/parse_stata_3sls_results.py, linearmodels/utility.py
Fix issues in testing and docs
Start removing .values and use asarray instead
=> Fix small issues

doc/source/changes.rst, linearmodels/iv/covariance.py, linearmodels/tests/iv/test_covariance.py
Fix high-lag parzen weights
closes #170
closes #168
=> Fix parzen weights

linearmodels/panel/model.py, linearmodels/tests/panel/test_fama_macbeth.py, linearmodels/utility.py
Correct rank check for block validity
Add warnings to explain potential issues
closes #176
=> BUG: Correct rank check for Fama-Macbeth

.travis.yml, linearmodels/iv/__init__.py, linearmodels/iv/covariance.py, linearmodels/iv/results.py, linearmodels/system/_utility.py, linearmodels/system/model.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/test_examples.py, linearmodels/utility.py, setup.cfg
Add 1.15 as a standard conda config
=> BLD: Update travis config

linearmodels/tests/panel/test_data.py, linearmodels/utility.py
Ensure categoricals are used to access itens with a CategoricalIndex
=> TST: Fix buggy test

doc/source/changes.rst, doc/source/conf.py, linearmodels/panel/model.py, linearmodels/panel/utility.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/panel/test_utility.py
Add optional estimation using LSMR.  This alternative may allow
extension to more than 2 effects.
=> ENH: Add support for LSMR

.travis.yml, doc/source/changes.rst, linearmodels/compat/numpy.py, linearmodels/panel/utility.py, linearmodels/tests/panel/test_utility.py, linearmodels/tests/test_compat.py
Add infrastructure to drop singletons
=> ENH: Add singleton dropping framework

doc/source/changes.rst, linearmodels/panel/model.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/panel/test_utility.py, linearmodels/utility.py
Enable dropping singleton observations
closes #191
=> ENH: Enable singleton observations to be dropped

linearmodels/panel/model.py, linearmodels/tests/panel/test_model.py
Improve the error message with a list of variables that appear to
either be absorbed or become collinear
closes #193
=> ENH: Improve absorbing effects error message

.travis.yml, linearmodels/panel/model.py, linearmodels/panel/utility.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/test_panel_ols.py
Correct indexation of cluster variable
Ensure collected effects always returns the expected type
Refactor duplicated and wrong code
Fix dummy creation to ensure dtype can handle data
Extend test data generation to handle sparse panels
Add extended tests of singleton dropping
=> BUG: Fix small bugs due to singleton dropping

doc/source/changes.rst, doc/source/conf.py, examples/panel_data-formats.ipynb, linearmodels/panel/model.py, linearmodels/panel/utility.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/panel/test_utility.py
Add precoditiioning for the dummy variable matrix for lsmr estimation
Fix a bug in an example notebook
=> ENH: Add preconditioning for lsmr estimation

MANIFEST.in, ci/install-from-pypi.sh, doc/source/changes.rst, linearmodels/panel/_utility.pyx, linearmodels/panel/utility.py, linearmodels/tests/panel/test_utility.py, setup.py
Add a cython module to improve performance when dropping singletons.
=> ENH: Add optional Cython path to perform 2-core graph selection

README.md, README.rst, requirements.txt, setup.py
Try to build with extension module and then bail out and go without
if missing
=> ENH: Improve setup to try to build cython

linearmodels/panel/model.py, linearmodels/tests/panel/test_panel_ols.py
Fix weight shape check in panels with repeated entries
=> BUG: Fix bug with weights in repeated panels

doc/source/changes.rst, linearmodels/panel/model.py, linearmodels/panel/utility.py, linearmodels/tests/panel/test_panel_ols.py
Add option that allows absorbed to be dropped
closes #205
=> ENH: Allow FE regression to drop absorbed

doc/source/spelling_wordlist.txt, examples/panel_data-formats.ipynb, linearmodels/tests/test_utility.py, linearmodels/utility.py
=> MAINT: Remove pd.Panel

.travis.yml, README.md, README.rst, ci/install-common.sh, doc/source/changes.rst, setup.py
Update requirements inline with NEP-29
Increase Python to 3.6
=> MAINT: Update requirements

.travis.yml, appveyor.yml, linearmodels/__init__.py, linearmodels/conftest.py, linearmodels/panel/utility.py, linearmodels/tests/asset_pricing/test_linear_factor_gmm.py, linearmodels/tests/asset_pricing/test_model.py, linearmodels/tests/iv/test_absorbing.py, linearmodels/tests/iv/test_covariance.py, linearmodels/tests/iv/test_model.py, linearmodels/tests/iv/test_postestimation.py, linearmodels/tests/panel/test_fama_macbeth.py, linearmodels/tests/panel/test_model.py, linearmodels/tests/panel/test_panel_covariance.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/system/test_gmm.py, linearmodels/tests/system/test_sur.py, setup.cfg
Add appveyor testing
Add smoke pytest decorator so they can be skipped
=> TST: Add smoke decorator and appveyor

doc/source/panel/reference.rst, linearmodels/asset_pricing/model.py, linearmodels/iv/data.py, linearmodels/panel/covariance.py, linearmodels/panel/model.py, linearmodels/panel/results.py, linearmodels/tests/iv/results/execute-stata-simulated-data.py, linearmodels/tests/iv/results/execute-stata.py
Expose all params for interested users
=> ENH: Expose all params for FamaMacBeth

doc/source/panel/reference.rst, linearmodels/panel/model.py, linearmodels/panel/results.py, linearmodels/tests/panel/test_fama_macbeth.py
Add a results class
closes #219
=> ENH: Expose all parmeter estimates for FMB

linearmodels/_version.py, linearmodels/asset_pricing/covariance.py, linearmodels/iv/model.py, linearmodels/system/covariance.py, linearmodels/system/gmm.py
Call the init to ensure attributes are added in init
=> MAINT: Ensure _HACMixin's init is called

doc/source/conf.py, doc/source/panel/reference.rst, linearmodels/compat/pandas.py, linearmodels/iv/model.py, linearmodels/panel/__init__.py, linearmodels/panel/covariance.py, linearmodels/panel/model.py, linearmodels/panel/results.py, linearmodels/panel/utility.py, linearmodels/tests/panel/test_utility.py, linearmodels/utility.py
Refactor to use explicity constructors
=> REF: Refactor covariance initialization

.lgtm.yml, .travis.yml, README.md, README.rst, doc/source/changes.rst, linearmodels/iv/model.py, linearmodels/iv/results.py, linearmodels/tests/iv/test_absorbing.py, linearmodels/tests/iv/test_results.py, linearmodels/tests/panel/test_panel_ols.py, pyproject.toml, requirements.txt
=> CLN: Complete typing

linearmodels/asset_pricing/model.py, linearmodels/asset_pricing/results.py, linearmodels/iv/absorbing.py, linearmodels/iv/model.py, linearmodels/iv/results.py, linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/panel/utility.py, linearmodels/system/_utility.py, linearmodels/system/gmm.py, linearmodels/system/model.py, linearmodels/tests/asset_pricing/test_model.py, linearmodels/tests/iv/results/read_stata_results.py, linearmodels/tests/iv/test_absorbing.py, linearmodels/tests/iv/test_postestimation.py, linearmodels/tests/panel/results/parse_stata_results.py, linearmodels/tests/panel/test_fama_macbeth.py, linearmodels/tests/system/results/parse_stata_results.py, linearmodels/tests/system/test_3sls.py, linearmodels/tests/system/test_covariance.py, linearmodels/tests/system/test_gmm.py, linearmodels/tests/system/test_sur.py, linearmodels/utility.py, setup.py
Correct issues identified by PyCharm
=> CLN: Correct typing issues

doc/source/changes.rst, linearmodels/iv/covariance.py
Reverse m_star tuning parameters in auto bandwidth selection
=> BUG: Correct tuning parameters

README.md, doc/source/index.rst, linearmodels/__init__.py, linearmodels/asset_pricing/__init__.py, linearmodels/panel/__init__.py, linearmodels/panel/results.py, linearmodels/system/__init__.py, linearmodels/typing/__init__.py
=> DOC: Add relationship to statsmodels

linearmodels/panel/model.py
Add a doc string for the fit method in the RandomEffects model
=> DOC: Add a docstring for fit in RE

doc/Makefile, doc/source/changes.rst, doc/source/conf.py, doc/source/panel/convert-lyx.cmd, doc/source/panel/mathematical-detail.lyx, doc/source/panel/mathematical-detail.txt, doc/source/spelling_wordlist.txt, examples/system_examples.ipynb, linearmodels/panel/model.py, linearmodels/panel/results.py, setup.py
Add measures that are similar to Stata
Add definition of R2 measures
closes #157
=> ENH: Add correlation-based R2 measures

linearmodels/iv/results.py, linearmodels/tests/iv/results/read_stata_results.py
Remove l which trigggers flake8 on 3.8
=> MAIN: Remove use of l

.travis.yml, linearmodels/iv/absorbing.py, linearmodels/iv/data.py, linearmodels/iv/results.py, linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/panel/results.py, linearmodels/shared/base.py, linearmodels/shared/io.py, linearmodels/tests/iv/test_data.py, linearmodels/tests/iv/test_model.py, linearmodels/tests/panel/test_model.py, linearmodels/tests/panel/test_results.py, linearmodels/tests/test_utility.py, setup.cfg
=> ENH: Add stars to comparrisons

linearmodels/asset_pricing/results.py, linearmodels/iv/results.py, linearmodels/panel/covariance.py, linearmodels/panel/model.py, linearmodels/panel/results.py, linearmodels/panel/utility.py, linearmodels/system/results.py, linearmodels/tests/panel/test_panel_ols.py
Raise an exception with all exog variables are absorbed
Handle case where Y is all 0 or is fully absorbed
closes #269
=> BUG: Raise when all exog variable have been fully abosrbed

.travis.yml, ci/install-common.sh, ci/install-prerelease.sh, linearmodels/asset_pricing/results.py, linearmodels/iv/results.py, linearmodels/panel/covariance.py, linearmodels/panel/results.py, linearmodels/system/results.py, linearmodels/tests/iv/test_model.py, linearmodels/tests/test_examples.py, setup.cfg
Defer weighting to OLS to get correct R2 value
closes #274
=> BUG: Correct first stage R2

.travis.yml
Add Cython to make sure code is compiled
=> TST: Add Cython to some test configs

linearmodels/iv/covariance.py, linearmodels/iv/results.py, linearmodels/panel/results.py, linearmodels/system/gmm.py
Correct spacing errors in lists
=> DOC: Fix spacing in lists

ci/install-common.sh, linearmodels/panel/model.py, requirements-dev.txt
Update for recent changes in mypy
=> MAINT: Update typing

linearmodels/panel/model.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/panel/test_results.py
Prodice a better exception when exog has issues
closes #291
closes #292
=> ENH: Improve error when using predict

.github/workflows/generate-documentation.yml, .gitignore, ci/push-docs-gh-pages.sh, requirements-dev.txt
Still a WIP. Needs a deploy strategy
=> MAINT: Use github actions to deploy docs to devel

doc/source/panel/convert-lyx.cmd, doc/source/panel/mathematical-detail.lyx, doc/source/panel/mathematical-detail.txt
=> DOC: Fix small typos in R2 docs

azure-pipelines.yml, ci/azure_template_posix.yml
=> MAINT: Add coverage

appveyor.yml, doc/source/changes.rst, examples/asset-pricing_examples.ipynb, examples/asset-pricing_formulas.ipynb, examples/iv_absorbing-regression.ipynb, examples/iv_advanced-examples.ipynb, examples/iv_basic-examples.ipynb, examples/iv_using-formulas.ipynb, examples/panel_data-formats.ipynb, examples/panel_examples.ipynb, examples/panel_using-formulas.ipynb, examples/system_examples.ipynb, examples/system_formulas.ipynb, examples/system_three-stage-ls.ipynb, linearmodels/iv/absorbing.py, linearmodels/tests/iv/test_absorbing.py, requirements.txt
Add HDFE for absorbing regression where relevant
=> ENH: Add HDFE for Absorbing

doc/source/changes.rst, doc/source/spelling_wordlist.txt, linearmodels/iv/absorbing.py, linearmodels/iv/common.py, linearmodels/iv/data.py
Release 4.18 commit with doc changes
=> RLS: Release 4.18

linearmodels/iv/results.py, linearmodels/panel/data.py, linearmodels/panel/model.py, linearmodels/panel/utility.py, linearmodels/shared/hypotheses.py, linearmodels/system/_utility.py, linearmodels/system/model.py, linearmodels/tests/iv/test_data.py, linearmodels/tests/iv/test_model.py, versioneer.py
=> MAINT: Update for NumPy type stubs

linearmodels/iv/results.py, linearmodels/panel/results.py
=> DOC: Improve docstring formatting

.github/workflows/generate-documentation.yml, linearmodels/asset_pricing/model.py, linearmodels/asset_pricing/results.py, linearmodels/iv/model.py, linearmodels/shared/utility.py, linearmodels/tests/asset_pricing/_utility.py, linearmodels/tests/asset_pricing/test_formulas.py, linearmodels/tests/iv/test_model.py
Add user optiosn to pass options
closes #313
=> ENH: Add minimize options and starting vals

linearmodels/panel/model.py, linearmodels/panel/utility.py, linearmodels/shared/linalg.py, linearmodels/tests/panel/test_panel_ols.py, setup.cfg
Ensure constant is retained in panel models when dropping absorbed
closes #318
=> BUG: Ensure constant col is retained when dropping

.github/workflows/generate-documentation.yml, README.md, azure-pipelines.yml, linearmodels/azure-pipelines.yml, versioneer.py
=> MAINT: Update for rename to main

linearmodels/iv/covariance.py, linearmodels/panel/model.py, linearmodels/panel/utility.py, linearmodels/system/_utility.py, linearmodels/system/covariance.py, linearmodels/system/gmm.py, linearmodels/system/model.py, linearmodels/tests/iv/results/simulated-test-data.py, linearmodels/tests/panel/results/generate-panel-data.py
=> MAINT: Improve typing

.coveragerc, ci/azure_template_posix.yml, ci/install-from-pypi.sh, ci/install-posix.sh, linearmodels/__init__.py, linearmodels/panel/covariance.py, linearmodels/panel/model.py, linearmodels/panel/utility.py, linearmodels/tests/panel/test_between_ols.py, linearmodels/tests/panel/test_firstdifference_ols.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/panel/test_pooled_ols.py, linearmodels/tests/panel/test_random_effects.py, linearmodels/tests/panel/test_results.py, linearmodels/tests/panel/test_utility.py, linearmodels/tests/shared/test_base.py, linearmodels/tests/shared/test_typed_getters.py, linearmodels/tests/shared/test_utility.py, setup.py
=> TST: Add test without cython

linearmodels/system/covariance.py, linearmodels/system/model.py, linearmodels/tests/system/test_sur.py
standard errors are homogeneous of degree 0 and so t-stats are not.
Fixes an issue with how the x'x matrix is constructed when using GLS
=> BUG: t-stats in SUR with GLS are not homogeneous deg 0

linearmodels/system/results.py, linearmodels/tests/panel/test_model.py, linearmodels/tests/system/test_sur.py
Add Breusch-Pagan test to SUR Results
closes #338
=> ENH: Add Breusch-Pagan test

doc/source/changes.rst, doc/source/names_wordlist.txt, doc/source/spelling_wordlist.txt, doc/source/system/convert-lyx.cmd, doc/source/system/mathematical-detail.lyx, doc/source/system/mathematical-detail.txt, linearmodels/panel/model.py, linearmodels/system/results.py, linearmodels/tests/system/test_sur.py
Add likelihood ratio test for diagonal covariance
xref #338
=> ENH: Add likelihood ratio test for SUR

examples/panel_examples.ipynb, linearmodels/panel/covariance.py, linearmodels/system/model.py, linearmodels/tests/panel/test_panel_ols.py
Add checks for specific covariance kwargs allowed
closes #342
=> ENH: Check covariance config kwargs

linearmodels/asset_pricing/model.py, linearmodels/shared/utility.py, requirements-test.txt
Correct swapped factors and portfolios.
=> BUG: Correct variable ordering

linearmodels/asset_pricing/covariance.py, linearmodels/asset_pricing/model.py, linearmodels/asset_pricing/results.py, linearmodels/iv/_utility.py, linearmodels/panel/covariance.py, linearmodels/shared/covariance.py, linearmodels/shared/exceptions.py, linearmodels/shared/linalg.py, linearmodels/shared/utility.py, linearmodels/system/_utility.py, linearmodels/system/covariance.py, linearmodels/system/gmm.py, linearmodels/system/model.py, linearmodels/system/results.py, linearmodels/typing/__init__.py
Improve specificity to for of ndarray dtypes
=> ENH: Improve typing specificity

examples/panel_examples.ipynb, linearmodels/panel/results.py, linearmodels/tests/panel/test_panel_ols.py
Correct the reported number of other effects
closes #350
=> BUG: COrrect other effects stats in summary

linearmodels/asset_pricing/results.py, linearmodels/system/results.py, linearmodels/tests/asset_pricing/test_linear_factor_model.py
Add pvalues
Fix formula that reported incorrect values in tables
closes #353
=> ENH: Add pvalues for asset pricing results

doc/source/changes.rst, linearmodels/iv/model.py, linearmodels/iv/results.py, linearmodels/panel/model.py, linearmodels/panel/results.py, linearmodels/shared/utility.py, linearmodels/system/model.py, linearmodels/system/results.py, linearmodels/tests/asset_pricing/test_formulas.py, linearmodels/tests/iv/test_absorbing.py, linearmodels/tests/iv/test_formulas.py, linearmodels/tests/panel/results/generate-panel-data.py, linearmodels/tests/panel/test_data.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/panel/test_utility.py, linearmodels/tests/system/test_3sls_against_stata.py, linearmodels/tests/system/test_formulas.py, linearmodels/tests/system/test_gmm.py, linearmodels/tests/system/test_sur.py, linearmodels/typing/__init__.py, requirements-dev.txt
Ensure corr squared is actually squared
Test against other R2 when identical
=> BUG: Correct corr squared

doc/source/_templates/autosummary/class.rst
Apply fix to remove duplicate methods section
=> DOC: Remove duplicate methods section

ci/azure_template_posix.yml, doc/source/changes.rst, linearmodels/panel/model.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/test_pooled_ols.py, pyproject.toml
Improve error when data sizes are not equal
Prepare for 4.25 release
=> ENH: Improve error for unequal data size

doc/source/changes.rst, examples/iv_basic-examples.ipynb, linearmodels/asset_pricing/model.py, linearmodels/iv/absorbing.py, linearmodels/iv/covariance.py, linearmodels/iv/model.py, linearmodels/panel/model.py, linearmodels/panel/utility.py, linearmodels/shared/exceptions.py, linearmodels/system/model.py, linearmodels/system/results.py, linearmodels/tests/asset_pricing/_utility.py, linearmodels/tests/iv/results/simulated-test-data.py, linearmodels/tests/iv/test_absorbing.py, linearmodels/tests/iv/test_covariance.py, linearmodels/tests/iv/test_formulas.py, linearmodels/tests/panel/_utility.py, linearmodels/tests/panel/test_utility.py, linearmodels/tests/system/_utility.py, linearmodels/tests/system/test_3sls_against_stata.py, requirements-dev.txt
Fix a bug where pandas structures with different indices would
produce NaN predictions
=> BUG: Fix a bug addecting IV predictions

examples/asset-pricing_examples.ipynb, examples/asset-pricing_formulas.ipynb, examples/iv_absorbing-regression.ipynb, examples/iv_advanced-examples.ipynb, examples/iv_basic-examples.ipynb, examples/iv_using-formulas.ipynb, examples/panel_data-formats.ipynb, examples/panel_examples.ipynb, examples/panel_using-formulas.ipynb, examples/system_examples.ipynb, examples/system_formulas.ipynb, examples/system_three-stage-ls.ipynb, linearmodels/tests/system/test_3sls.py
Add example to notebook
Reformat notebooks
=> DOC: Show example of predict in 3SLS

ci/azure_template_posix.yml, linearmodels/panel/model.py, linearmodels/tests/panel/test_utility.py, requirements.txt
Update code for changes in formulaic 0.3.x
Pin to latest in 0.3.x branch
closes #412
=> MAINT: Update for changes in formulic

doc/source/changes.rst
=> RLS: Release 4.26

doc/source/panel/index.rst, examples/asset-pricing_formulas.ipynb, examples/iv_basic-examples.ipynb, examples/iv_using-formulas.ipynb, examples/panel_using-formulas.ipynb, examples/system_formulas.ipynb, linearmodels/iv/results.py, linearmodels/panel/results.py, requirements.txt, setup.cfg
Remove mentions of patsy and replace with formulaic
=> MAINT: Remove references to patsy

doc/source/changes.rst, doc/source/conf.py, doc/source/index.rst, linearmodels/iv/_utility.py, linearmodels/iv/absorbing.py, linearmodels/iv/covariance.py, linearmodels/iv/results.py, linearmodels/panel/model.py, linearmodels/panel/results.py
Fix bug
Fix docstring examples
=> BUG: Fix bug when creating model from formula with missing data

linearmodels/iv/results.py, linearmodels/shared/hypotheses.py, linearmodels/tests/iv/test_absorbing.py, linearmodels/tests/iv/test_postestimation.py, linearmodels/tests/panel/test_results.py
Use formulaic in place of patsy
=> ENH: Move to formulaic for hypothesis testing

linearmodels/tests/asset_pricing/test_formulas.py, linearmodels/tests/iv/test_formulas.py, linearmodels/tests/panel/test_formula.py, linearmodels/tests/system/test_formulas.py
Ensure IV works with escaped variable names
=> TST: Add test for escaped variable names in IV

linearmodels/tests/iv/test_absorbing.py, linearmodels/typing/__init__.py, linearmodels/typing/data.py
pragma out incoverable
Add a couple of tests
=> MAINT: Improver covreage

.github/workflows/cron-test.yml
https://github.com/actions/setup-python/releases
=> Upgrade GitHub Actions setup-python

ci/azure_template_posix.yml, doc/source/changes.rst, doc/source/index.rst, examples/asset-pricing_formulas.ipynb, examples/iv_basic-examples.ipynb, examples/iv_using-formulas.ipynb, examples/panel_using-formulas.ipynb, examples/system_formulas.ipynb, examples/system_three-stage-ls.ipynb, linearmodels/compat/formulaic.py, linearmodels/iv/_utility.py, linearmodels/iv/absorbing.py, linearmodels/panel/model.py, linearmodels/panel/results.py, linearmodels/system/model.py, linearmodels/system/results.py, linearmodels/tests/iv/test_formulas.py, linearmodels/tests/panel/test_formula.py, linearmodels/tests/system/results/execute-stata-3sls.py, linearmodels/tests/system/results/generate_data.py, linearmodels/tests/system/test_formulas.py
Update to latest release
Add __future__ module
closes #521
=> ENH: Update formulaic to 0.6

doc/source/changes/5.0.rst, linearmodels/panel/model.py, linearmodels/tests/panel/test_panel_ols.py
=> BUG: Correct entity and time count

linearmodels/panel/utility.py, linearmodels/tests/panel/test_utility.py
=> MAINT: Upadte type comparrison

doc/source/changes/5.0.rst, doc/source/conf.py
=> RLS: Update docs

ci/azure_template_posix.yml, doc/source/changes/5.0.rst, linearmodels/tests/system/test_formulas.py, requirements.txt, setup.py
Build on Python 3.12
Bump formulaic minimum
=> RLS: Release 5.3

ci/install-posix.sh, linearmodels/tests/panel/test_between_ols.py, linearmodels/tests/panel/test_fama_macbeth.py, linearmodels/tests/panel/test_firstdifference_ols.py, linearmodels/tests/panel/test_panel_ols.py, linearmodels/tests/panel/test_random_effects.py, requirements-test.txt, setup.cfg
Convert to series to avoid change dtypes
Add pyarrow for testing
=> MAINT: Avoid dtype changing insert

examples/iv_basic-examples.ipynb, examples/panel_examples.ipynb, examples/system_examples.ipynb, requirements-dev.txt
Fix small issues identified by ruff
Improve typing
=> MAINT: Clean up code

linearmodels/iv/absorbing.py
Fix a bug when using sha256 introuced to improve typing
=> TYP: Fix typing support
